preload = /home/marco/.config/wallpapers/gruvbox-backwater.jpg

wallpaper {
    monitor =
    path = /home/marco/.config/wallpapers/gruvbox-backwater.jpg
    fit_mode = cover
}

ipc = on
splash = false
splash_offset = 2
